# Title:
#   Open Source Rover (OSR) Drive Wheel Controllers
#
# Description:
#   Controllers for the motors driving the wheels
#
# Version:
#   v1.0.0, 03/2023
#
# Tested with:
#   ROS Noetic
#   Linux Ubuntu, 20.04 LTS
#
front_left_wheel_controller:
  type: effort_controllers/JointVelocityController
  joint: front_left_drive_joint
  pid: {p: 2, i: 10, d: 0}

front_right_wheel_controller:
  type: effort_controllers/JointVelocityController
  joint: front_right_drive_joint
  pid: {p: 2, i: 10, d: 0}

middle_left_wheel_controller:
  type: effort_controllers/JointVelocityController
  joint: middle_left_drive_joint
  pid: {p: 2, i: 10, d: 0}

middle_right_wheel_controller:
  type: effort_controllers/JointVelocityController
  joint: middle_right_drive_joint
  pid: {p: 2, i: 10, d: 0}

back_left_wheel_controller:
  type: effort_controllers/JointVelocityController
  joint: back_left_drive_joint
  pid: {p: 2, i: 10, d: 0}

back_right_wheel_controller:
  type: effort_controllers/JointVelocityController
  joint: back_right_drive_joint
  pid: {p: 2, i: 10, d: 0}
