front_left_wheel_controller:
  type: effort_controllers/JointVelocityController
  joint: front_left_drive_joint
  pid: {p: 10, i: 0, d: 0}

front_right_wheel_controller:
  type: effort_controllers/JointVelocityController
  joint: front_right_drive_joint
  pid: {p: 10, i: 0, d: 0}

middle_left_wheel_controller:
  type: effort_controllers/JointVelocityController
  joint: middle_left_drive_joint
  pid: {p: 10, i: 0, d: 0}

middle_right_wheel_controller:
  type: effort_controllers/JointVelocityController
  joint: middle_right_drive_joint
  pid: {p: 10, i: 0, d: 0}

back_left_wheel_controller:
  type: effort_controllers/JointVelocityController
  joint: back_left_drive_joint
  pid: {p: 10, i: 0, d: 0}

back_right_wheel_controller:
  type: effort_controllers/JointVelocityController
  joint: back_right_drive_joint
  pid: {p: 10, i: 0, d: 0}
