# Title:
#   Open Source Rover (OSR) State Controller
#
# Description:
#   This controller publishes the state of all resources registered to a
#   hardware_interface::JointStateInterface to a topic of type sensor_msgs/JointState.
#
# Version:
#   v1.0, 03/2023
#
# Tested with:
#   ROS Noetic, Linux Ubuntu 20.04 LTS
#

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
