# Title:
#   Open Source Rover (OSR) Corner Controllers
#
# Description:
#   Controller for the corner motors responsible for steering
#
# Version:
#   v1.0, 03/2023
#
# Tested with:
#   ROS Noetic, Linux Ubuntu 20.04 LTS
#

front_left_corner_controller:
  type: effort_controllers/JointPositionController
  joint: front_left_corner_joint
  pid: {p: 10, i: 0, d: 0}

front_right_corner_controller:
  type: effort_controllers/JointPositionController
  joint: front_right_corner_joint
  pid: {p: 10, i: 0, d: 0}

back_left_corner_controller:
  type: effort_controllers/JointPositionController
  joint: back_left_corner_joint
  pid: {p: 10, i: 0, d: 0}

back_right_corner_controller:
  type: effort_controllers/JointPositionController
  joint: back_right_corner_joint
  pid: {p: 10, i: 0, d: 0}
