# Title:
#   Open Source Rover (OSR) Physical Properties
#
# Description:
#   Values with properties of the rover, used in the code.
#
# Version:
#   v1.0, 03/2023
#
# Tested with:
#   ROS Noetic, Linux Ubuntu 20.04 LTS
#
rover_dimensions:
  d1: 0.184  # [m]
  d2: 0.267  # [m]
  d3: 0.267  # [m]
  d4: 0.2556  # [m]
  wheel_radius: 0.075  # [m]

drive_no_load_rpm: 223  # no load speed for the drive motors
