#  
# Title:
#  Open Source Lunar Rover (OSLR) - Steer message file
#
# Author(s):
#   andyjak
#
# Version:
#   0.0.1, 08/2023
#
# Purpose:
#   Define message for corner wheel commands.
#
# Notes:
#   More information about messages can be found in [27].
#
# Test setup:
#   - ROS Noetic
#   - Ubuntu, 20.04 LTS
#   - Python 3.8.10
#
# References:
#   References are listed in the README.
#   Comments that include a [number] refers to the index in the reference list.
#

float64 left_front_pos
float64 left_back_pos
float64 right_front_pos
float64 right_back_pos